blocks:
  - materials:
      - "minecraft:blackstone": 1
      - "minecraft:lava": 1
      - "minecraft:basalt": 1
      - "minecraft:lava": 1
      - "minecraft:basalt": 1
      - "minecraft:lava": 1
      - "minecraft:basalt": 1
      - "minecraft:lava": 1
      - "minecraft:basalt": 1
      - "minecraft:lava": 1
      - "minecraft:basalt": 1
      - "minecraft:lava": 1
      - "minecraft:magma_block": 1
      - "minecraft:lava": 1
    layers: 2
  - materials:
      - "minecraft:blackstone": 2
      - "minecraft:basalt": 10
      - "minecraft:magma_block": 2
    layers: 2
  - materials:
      - "minecraft:netherrack": 1
    layers: 1
id: DELTA_LAVA
simplex: true
frequency: 0.1