blocks:
  - materials:
      - "minecraft:soul_sand": 1
      - "minecraft:soul_soil": 3
    layers: 4
  - materials:
      - "minecraft:netherrack": 1
    layers: 1
id: SOUL
simplex: true
frequency: 0.05