blocks:
  - materials:
      - "minecraft:basalt": 1
      - "minecraft:air": 1
    layers: 1
  - materials:
      - "minecraft:basalt": 1
    layers: 1
id: BASALT
spawnable:
  - "minecraft:basalt"
  - "minecraft:soul_sand"
  - "minecraft:soul_soil"
replaceable:
  - "minecraft:air"